---
- hosts: web-servers
  become: true
  tasks:
    - name: Copy war onto tomcat server
      copy:
            src: /opt/target/sfinder-0.0.1-SNAPSHOT.war
            dest: /root/opt/apache-tomcat-8.5.47/webapps
...
